# Generated by Django 6.0.1 on 2026-01-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
